# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib linaldb, .registration = TRUE
NULL

#' Embedded LINALDB engine -- wraps `TensorDb` directly, in-process, no
#' HTTP server. See `linal_embedded_db()` (R/api.R) for the public
#' constructor; this raw `#[extendr]` type is not meant to be constructed
#' directly from R.
#'
#' @section Methods:
#'\subsection{Method `dataset_dir`}{
#'`{data_dir}/{active_db}/datasets/{name}` -- the on-disk package
#'directory a `SAVE DATASET <name>` write lands in
#'(`src/core/storage.rs`), single source of truth for the R-side
#'`linal_embedded_dataset_*` readers so the path logic isn't
#'duplicated in Rust and R. Built via a real path join (not string
#'concatenation) so the returned string uses native separators on
#'every platform, matching R's own `file.path()` on the caller side.
#'}
#'
Db <- new.env(parent = emptyenv())

Db$new <- function(data_dir) .Call(wrap__Db__new, data_dir)

Db$execute <- function(sql) .Call(wrap__Db__execute, self, sql)

Db$active_db <- function() .Call(wrap__Db__active_db, self)

Db$data_dir <- function() .Call(wrap__Db__data_dir, self)

Db$dataset_dir <- function(name) .Call(wrap__Db__dataset_dir, self, name)

#' @export
`$.Db` <- function (self, name) { func <- Db[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Db` <- `$.Db`

# nolint end
